
version: "3"

services:
    app:
        build:
            context: .
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        # tty: true
        depends_on:
            - mysql
            - phpmyadmin
    mysql:
        image: mysql:8
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            TZ: 'Asia/Tokyo'
        volumes:
            - ./mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:5
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
